version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: websitebuilder-backend
    ports:
      - "8000:8000"
    volumes:
      - shared-public:/app/frontend-public
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: websitebuilder-frontend
    ports:
      - "5173:5173"
    volumes:
      - shared-public:/app/public
    networks:
      - app-network

volumes:
  mysql-data:
  shared-public:

networks:
  app-network:
    driver: host
