CREATE TABLE product (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_CATEGORY VARCHAR(255) NOT NULL,
    SVG_ICON TEXT,
    PRODUCT_DESCRIPTION TEXT,
    LEARN_MORE BOOLEAN NOT NULL DEFAULT 0,
    LEARN_MORE_LINK VARCHAR(255)
);
