CREATE TABLE footer_section (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SECTION_HEADER VARCHAR(255) NOT NULL,
    SECTION_ITEM_NAME VARCHAR(255) NOT NULL,
    LINK_TYPE VARCHAR(50) NOT NULL,
    LINK VARCHAR(255) NOT NULL
);
