CREATE TABLE email_settings (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FROM_MAIL VARCHAR(255) NOT NULL,
    TO_MAIL VARCHAR(255) NOT NULL,
    SMTP_HOST VARCHAR(255) NOT NULL,
    SMTP_PORT INT NOT NULL,
    SMTP_USERNAME VARCHAR(255) NOT NULL,
    SMTP_PASSWORD VARCHAR(255) NOT NULL
);
