CREATE TABLE footer_header (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TAGLINE VARCHAR(255) NOT NULL,
    SHOW_NEWSLETTER BOOLEAN NOT NULL,
    NEWSLETTER_HEADER_TEXT VARCHAR(255),
    NEWSLETTER_TAGLINE VARCHAR(255),
    COPYRIGHT_TEXT TEXT NOT NULL
);
