CREATE TABLE price (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PRICE_TAGLINE VARCHAR(255) NOT NULL,
    PLAN_TYPE VARCHAR(255) NOT NULL,
    CURRENCY_TYPE VARCHAR(10) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    OFFER BOOLEAN NOT NULL,
    OFFER_PRICE DECIMAL(10, 2),
    FEATURES_INCLUDED TEXT,
    FEATURES_EXCLUDED TEXT,
    CTA_BUTTON_TEXT VARCHAR(255),
    CTA_BUTTON_LINK VARCHAR(255)
);
